name: Static Web CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Build project
      run: |
        cd vite-react
        npm install
        npm run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./vite-react/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: vite-react/dist

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_CALENDS_RG }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name calendsliteapi --auth-mode key -d '$web' -s ./vite-react/dist --overwrite
        # THIS step can be added later to handle the Custom domain
        # - name: Purge CDN endpoint
        #   uses: azure/CLI@v1
        #   with:
        #     inlineScript: |
        #        az cdn endpoint purge --content-paths  "/*" --profile-name "cdnprofile2kjoo37i24nsw" --name "staticweb2kjoo37i24nsw" --resource-group "bucklin-portfolio-RG"

      # Azure logout
    - name: logout
      run: |
        az logout
      if: always()
